import Head from "next/head";
import type { NextPage } from "next";
import { IconSun, IconMoonStars } from "@tabler/icons";
import { ActionIcon, Center, Container, Grid, Text, useMantineColorScheme } from "@mantine/core";

const Home: NextPage = () => {
  const { colorScheme, toggleColorScheme } = useMantineColorScheme();
  const dark = colorScheme === "dark";

  return (
    <>
      <Head>
        <title>Next + TypeScript + Mantine UI + Prettier + ESlint</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Grid sx={{ minHeight: "100vh", alignContent: "center", justifyContent: "center" }}>
          <Grid.Col>
            <Center>
              <ActionIcon
                variant="outline"
                color={dark ? "yellow" : "blue"}
                onClick={() => toggleColorScheme()}
                title="Toggle color scheme"
              >
                {dark ? <IconSun size={18} /> : <IconMoonStars size={18} />}
              </ActionIcon>
            </Center>
          </Grid.Col>
          <Grid.Col>
            <Text align="center" weight="bold" sx={{ fontSize: "24px" }}>
              Next + TypeScript + Mantine UI + Prettier + ESlint
            </Text>
          </Grid.Col>
        </Grid>
      </Container>
    </>
  );
};

export default Home;
